language: node_js
node_js:
- '8'
- '7'
env:
  global:
  - secure: "ZecJTRwlcypnoka8jSnmKdL6Ss8w7WEFDR6U7UrfTfPKrmp5WR/HkyOEWjXb+yr1Zy9gs3XVByKCzH+KZlNTZ8bTaC/DljbSM2ePogTEybCMXMMuimpZz+uQaVDqrLwEhRfB75hbrNlV34sXKOWtaGPOG6lmp4+zwC/dxXxC3wECqIdEFc6YIEDidpDLZFd/H9TtBIywUN+qiqGBzmGe8KxCjSCByQj+8OABNJD/5ckgpjpyeQ7gLDtIH5t/whPuz39n8tBPHyOuvafxDK93Nll/wAnvstmOb4WgO7tBjK+7cbjIl8XPizU7L8lDSnU2Cbq7yOl0cT7df2IhD1sP1cfhMFrM1VxD875zMDROt4MmdqCKaxi824juATpM4DDJ33xTdFHCW9O9ta9IzV/h7smUQao8KpmpfaTcbgzeRAsXSzasdTM5M2mL8vn5dYq26Py/s1hDBeNvPKrdkOeiJXM3PBOodHkCN00D2k6sR+ZCYbM5mUJB+iAJfX0KnbDCW8BQ27rgzlFacRKusknl0MHmJCzV3HXsYadSxkwh+7x9YfJnh47GaViKPDbaRTTJBSjneZVmsrXMEFO9iHGU4OOHeQEaPEQ9d06BEsO2i1QAyFr98qm8w6DlgNTQWPvM+Txyjpr5H4v+XyZU6pVgTbGgGor+74ttfdeidVbXj6g="
jobs:
  include:
  - stage: Build
    if: tag IS PRESENT
    repo: oliverroick/travis-and-npm
    node_js: '8'
    script: npm run build
  - stage: NPM release
    if: tag IS PRESENT
    repo: oliverroick/travis-and-npm
    node_js: '8'
    script:
      - npm run build
    skip_cleanup: true
    deploy:
      provider: script
      script: ./deploy.sh
      on:
        tags: true
        repo: oliverroick/travis-and-npm
