language: node_js
node_js:
- '8'
jobs:
  include:
  - stage: NPM release
    if: tag IS PRESENT
    repo: oliverroick/travis-and-npm
    node_js: '8'
    script:
      - npm run build
    skip_cleanup: true
    before_deploy:
      - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
      - echo $PACKAGE_VERSION
      - |
        if [[ "$PACKAGE_VERSION" != "$TRAVIS_TAG" ]]; then
          echo "Git and NPM versions do not match. Have you updated package.json?"
          exit 1
        fi;
    deploy:
      provider: npm
      email: oliver.roick@gmail.com
      api_key:
        secure: HtMEt71AhI+gib3p9UnDohGi5z9V1Ps0js9A0cbjQHJSKnt+WF1DIy7rDAbc8lUOP28HYa8gXIUcA1PTLJH4MEPJBdTmbAPgkmBNGd5kRNCgJ5Y8viZms1sWP1Si0Asu1eaSH3360inDk40Jt18bGZQJ9UuzCuqYa+btbYEEJQrDlRRpdJDHhj+5bblvcmwQJEylFXdAeWWFhJvha8vWlGGPhW4wlVMxOtF5zrzAtzw8UbJAxyQNvgdrxMn/7i3OUlNTb5h2t8IQcdUpaIvRAw0C3f0oGS5bxN44SmByLwV8Lh2hVRqLqXGyJnMJdFfFYUXBaU3SMEBBUPJRAH0H6+N08jjoENvGms5ra0ZqUos/uyUpYtjvlj0D8Tay2gq3QaDkNtkA2OFJ3Q6JG98Xf6A75WYEu8g1EeGW3hZypwUXCTnwjjrcfDnJ1P77A/S6N2m1/tf2ezHDd8rsnocn0ZUFcUnr5uUdz7vm+cdmgJHot+JW8Us9iKMWusiC5FcU8O7NTloH8J/ZHV7jaBNpLj31X3IgtB09fRkU5lm3MmLiUMuk9xrNlQqv97oDngx6ae8j5jgJ7F7l+bSPF9RIuoX1QU0aDMa+hl88xeQgQ8PlWcKYkyXCyOt+SfunuGjU+mD977jBN4dPkTaNbuBVlsljsENZwUWSZVUuSn9s62o=
      on:
        tags: true
        repo: oliverroick/travis-and-npm
